
const HEADER_MAX_HEIGHT = 120;
const HEADER_MIN_HEIGHT = 70;
const PROFILE_IMAGE_MAX_HEIGHT = 80;
const PROFILE_IMAGE_MIN_HEIGHT = 40;

export { 
    HEADER_MAX_HEIGHT,
    HEADER_MIN_HEIGHT,
    PROFILE_IMAGE_MAX_HEIGHT,
    PROFILE_IMAGE_MIN_HEIGHT
} 